const diabetesPrevention = [
  {
    percentage: 0.1,
    suggestions: [
      "Limit intake of processed foods, sugary snacks, and beverages high in added sugars. These can cause rapid spikes in blood sugar levels and contribute to insulin resistance.",
      "Include healthy fats, such as those found in nuts, seeds, avocados, and fatty fish, in your diet. These fats can help improve insulin sensitivity and promote heart health.",
      "Stay hydrated by drinking plenty of water throughout the day. Dehydration can affect blood sugar levels and contribute to fatigue and other symptoms.",
      "Manage stress through relaxation techniques such as deep breathing, meditation, or yoga. Chronic stress can impact blood sugar levels and increase the risk of developing diabetes.",
      "Get regular check-ups with your healthcare provider to monitor other risk factors for diabetes, such as blood pressure and cholesterol levels. Addressing these factors early can help prevent or delay the onset of diabetes.",
      "Limit alcohol consumption, as it can interfere with blood sugar regulation and contribute to weight gain. If you choose to drink, do so in moderation and with food to help mitigate its effects.",
      "Ensure you're getting enough sleep each night, aiming for 7-9 hours for most adults. Poor sleep habits can disrupt hormone levels and affect blood sugar control.",
      "Consider meeting with a registered dietitian or nutritionist to develop a personalized meal plan that meets your dietary preferences and health goals. They can provide guidance on portion control, carbohydrate counting, and meal timing to help manage blood sugar levels.",
    ],
  },
  {
    percentage: 0.2,
    suggestions: [
      "Incorporate more leafy greens, such as spinach, kale, and Swiss chard, into your meals. These vegetables are rich in nutrients and fiber, which can help regulate blood sugar levels.",
      "Limit consumption of red and processed meats, which have been linked to an increased risk of type 2 diabetes. Choose lean protein sources such as poultry, fish, tofu, and legumes more often.",
      "Practice mindful eating by paying attention to hunger and fullness cues. Avoid distractions while eating, such as watching TV or using electronic devices, to prevent overeating.",
      "Experiment with different cooking methods, such as steaming, baking, grilling, or sautéing, to prepare meals without excessive added fats or oils.",
      "Stay consistent with your physical activity routine, aiming for at least 150 minutes of moderate-intensity aerobic activity or 75 minutes of vigorous-intensity activity per week. Incorporate strength training exercises on two or more days per week to build muscle mass and improve insulin sensitivity.",
      "Monitor your weight regularly and make adjustments to your diet and exercise routine as needed to maintain a healthy weight. Even modest weight loss can improve insulin sensitivity and reduce the risk of diabetes.",
      "Keep track of your daily carbohydrate intake and choose complex carbohydrates, such as whole grains, legumes, and starchy vegetables, over refined carbohydrates whenever possible. These foods have a lower glycemic index and are less likely to cause spikes in blood sugar levels.",
      "Consider joining a diabetes prevention program or support group to connect with others who are also working to reduce their risk of developing diabetes. Peer support and accountability can be valuable in maintaining motivation and adherence to healthy habits.",
    ],
  },
  {
    percentage: 0.3,
    suggestions: [
      "Prioritize regular meal timing and spacing throughout the day to help stabilize blood sugar levels. Aim to eat balanced meals every 3-4 hours, including breakfast, lunch, dinner, and healthy snacks as needed.",
      "Limit intake of high-calorie, low-nutrient foods such as fast food, fried foods, and sugary desserts. These foods can contribute to weight gain and increase the risk of insulin resistance.",
      "Practice portion control by using smaller plates, bowls, and utensils to help prevent overeating. Aim to fill half of your plate with non-starchy vegetables, one-quarter with lean protein, and one-quarter with whole grains or starchy vegetables.",
      "Incorporate resistance training exercises, such as weightlifting or bodyweight exercises, into your fitness routine to build muscle mass and improve glucose metabolism. Aim for at least two sessions per week.",
      "Stay hydrated by drinking water throughout the day, especially before and during exercise. Avoid sugary beverages and excessive caffeine, as they can affect blood sugar levels and hydration status.",
      "Monitor your blood pressure regularly and take steps to keep it within a healthy range. High blood pressure can increase the risk of cardiovascular complications associated with diabetes.",
      "Limit screen time and sedentary activities, such as watching TV or using electronic devices, to reduce the risk of weight gain and promote physical activity. Take breaks to stand, stretch, and move throughout the day.",
      "Work with a healthcare provider to develop an individualized diabetes prevention plan that addresses your specific risk factors, medical history, and lifestyle preferences. This may include medication management, if appropriate, along with dietary and lifestyle modifications.",
    ],
  },
  {
    percentage: 0.4,
    suggestions: [
      "Focus on increasing your intake of fiber-rich foods such as fruits, vegetables, whole grains, and legumes. Fiber helps regulate blood sugar levels and promotes satiety, reducing the risk of overeating.",
      "Limit consumption of high-glycemic index foods, such as white bread, white rice, and sugary cereals, which can cause rapid spikes in blood sugar levels. Opt for low-glycemic index alternatives whenever possible.",
      "Incorporate more plant-based protein sources into your diet, such as beans, lentils, tofu, and tempeh. Plant-based proteins are lower in saturated fat and may have additional health benefits for diabetes prevention.",
      "Practice stress-reduction techniques such as deep breathing exercises, progressive muscle relaxation, or mindfulness meditation. Chronic stress can contribute to insulin resistance and worsen blood sugar control.",
      "Prioritize sleep hygiene by establishing a consistent sleep schedule, creating a relaxing bedtime routine, and optimizing your sleep environment. Aim for 7-9 hours of quality sleep per night.",
      "Consider working with a registered dietitian or certified diabetes educator to develop a personalized meal plan that meets your nutritional needs and promotes stable blood sugar levels. They can provide guidance on carbohydrate counting, meal timing, and portion control.",
      "Engage in regular physical activity that you enjoy, such as walking, dancing, gardening, or playing sports. Find activities that fit your interests and lifestyle to make exercise a sustainable habit.",
      "Stay informed about diabetes risk factors, symptoms, and preventive strategies by attending educational workshops, reading reputable sources, and staying connected with healthcare professionals. Knowledge is power when it comes to managing your health.",
    ],
  },
  {
    percentage: 0.5,
    suggestions: [
      "Prioritize regular blood sugar monitoring, especially if you have a family history of diabetes or other risk factors. Keep track of your readings and share them with your healthcare provider to adjust your management plan as needed.",
      "Focus on building a strong support network of family, friends, and healthcare professionals who can provide encouragement, accountability, and guidance in managing your health.",
      "Experiment with meal timing strategies, such as intermittent fasting or time-restricted eating, under the guidance of a healthcare provider. These approaches may help improve insulin sensitivity and blood sugar control.",
      "Incorporate stress-reducing activities into your daily routine, such as yoga, tai chi, or guided imagery. Find relaxation techniques that resonate with you and make them a regular part of your self-care practice.",
      "Stay vigilant about foot care and skin health, as people with diabetes are at increased risk of foot ulcers, infections, and other complications. Inspect your feet daily for any cuts, sores, or changes, and seek prompt medical attention for any concerns.",
      "Explore complementary and alternative therapies, such as acupuncture, massage therapy, or herbal supplements, to complement conventional diabetes management strategies. Consult with a qualified practitioner to ensure safety and effectiveness.",
      "Join a diabetes support group or online community to connect with others who share similar experiences and challenges. Sharing knowledge, resources, and emotional support can help you feel empowered and less alone in your journey.",
    ],
  },
  {
    percentage: 0.6,
    suggestions: [
      "Educate yourself about the potential complications of diabetes, such as heart disease, stroke, kidney disease, and vision problems. Understanding the risks can motivate you to take proactive steps to manage your health.",
      "Work closely with a healthcare team that includes a primary care physician, endocrinologist, dietitian, and exercise physiologist. Collaborate with each member to develop a comprehensive diabetes management plan tailored to your individual needs and preferences.",
      "Stay up-to-date on the latest research and advancements in diabetes prevention and treatment. Attend seminars, webinars, or conferences to learn from experts in the field and explore new strategies for managing your condition.",
      "Develop a contingency plan for managing blood sugar fluctuations during illness, stress, or other challenging situations. Work with your healthcare provider to create personalized guidelines for adjusting medication dosages, monitoring blood sugar levels, and seeking medical assistance when needed.",
      "Stay connected with loved ones and communicate openly about your diabetes management journey. Share your concerns, victories, and challenges with trusted friends and family members who can offer support, encouragement, and practical assistance as needed.",
      "Practice self-compassion and resilience in the face of setbacks or challenges. Remember that managing diabetes is a lifelong journey, and it's normal to experience ups and downs along the way. Celebrate your progress and accomplishments, no matter how small.",
      "Engage in regular physical activity that you enjoy, such as walking, cycling, swimming, or dancing. Aim for at least 150 minutes of moderate-intensity aerobic activity per week, along with muscle-strengthening exercises on two or more days.",
      "Monitor your blood pressure and cholesterol levels regularly, as both are important risk factors for cardiovascular complications associated with diabetes. Work with your healthcare provider to develop strategies for managing these risk factors through lifestyle modifications and, if necessary, medication.",
    ],
  },
  {
    percentage: 0.7,
    suggestions: [
      "Create a supportive environment at home and work that promotes healthy habits and reduces temptation. Surround yourself with positive influences and remove barriers to healthy living, such as unhealthy snacks or sedentary behaviors.",
      "Track your food intake, physical activity, blood sugar levels, medication adherence, and other relevant data in a journal or mobile app. Monitoring your progress over time can help you identify patterns, set goals, and make informed decisions about your health.",
      "Stay informed about the latest guidelines for diabetes management, prevention, and treatment. Consult reputable sources such as professional organizations, government agencies, and medical journals for evidence-based information.",
      "Consider participating in research studies or clinical trials related to diabetes prevention and treatment. By contributing to scientific knowledge, you may gain access to cutting-edge therapies, interventions, or support services.",
      "Seek emotional support from a licensed therapist, counselor, or psychologist if you're feeling overwhelmed, anxious, or depressed about your diabetes diagnosis or risk. Mental health is an essential component of overall well-being and should be addressed proactively.",
      "Stay active throughout the day by incorporating movement into your daily routine. Take short walking breaks, use a standing desk, or engage in household chores or gardening to avoid prolonged periods of sitting.",
      "Maintain a positive outlook and focus on what you can control rather than dwelling on limitations or setbacks. Set realistic goals, celebrate achievements, and practice gratitude for the blessings in your life.",
      "Stay connected with healthcare providers who specialize in diabetes management, such as endocrinologists, certified diabetes educators, and registered dietitians. Regular check-ups and ongoing communication can help you stay on track with your treatment plan and address any concerns promptly.",
    ],
  },
  {
    percentage: 0.8,
    suggestions: [
      "Consult with a healthcare provider to assess your individual risk factors and discuss potential preventive medications. Some medications, such as metformin, may be recommended for individuals at high risk of developing diabetes to help lower blood sugar levels and improve insulin sensitivity.",
      "Be proactive in addressing any underlying health conditions that may increase your risk of diabetes, such as high blood pressure or high cholesterol. Follow your healthcare provider's recommendations for managing these conditions through lifestyle modifications and, if necessary, medication.",
      "Participate in structured diabetes prevention programs that offer education, support, and accountability. These programs typically focus on lifestyle modifications such as healthy eating, physical activity, and weight management, and may include group sessions, individual counseling, or online resources.",
      "Stay engaged in your healthcare journey by asking questions, seeking clarification, and advocating for your needs during medical appointments. Be proactive in discussing concerns, treatment options, and goals with your healthcare team to ensure that your care plan aligns with your preferences and values.",
      "Stay informed about emerging research, treatment options, and support services related to diabetes prevention and management. Explore reputable sources such as medical journals, professional organizations, and patient advocacy groups for up-to-date information and resources.",
      "Engage in regular physical activity that you enjoy and can maintain over the long term. Find activities that fit your interests, schedule, and physical abilities, whether it's walking, swimming, cycling, dancing, or participating in team sports.",
      "Prioritize stress management techniques such as deep breathing exercises, progressive muscle relaxation, or mindfulness meditation. Chronic stress can impact blood sugar levels and overall health, so finding healthy ways to cope with stress is essential for diabetes prevention.",
      "Stay connected with friends, family, and other support networks who can provide encouragement, empathy, and practical assistance as needed. Share your concerns, victories, and challenges openly and seek help when necessary.",
    ],
  },
  {
    percentage: 0.9,
    suggestions: [
      "Create a detailed action plan with the guidance of a healthcare provider to address your high risk of developing diabetes. This plan should include specific goals, strategies, and timelines for implementing lifestyle changes, monitoring progress, and seeking medical intervention if necessary.",
      "Follow a structured meal plan that emphasizes whole, unprocessed foods and limits added sugars, refined carbohydrates, and unhealthy fats. Work with a registered dietitian to develop a personalized eating plan tailored to your nutritional needs and preferences.",
      "Engage in regular physical activity to improve insulin sensitivity, lower blood sugar levels, and maintain a healthy weight. Aim for at least 150 minutes of moderate-intensity aerobic exercise or 75 minutes of vigorous-intensity exercise per week, along with muscle-strengthening activities on two or more days.",
      "Monitor your blood sugar levels closely using a glucometer or continuous glucose monitoring system. Keep track of your readings, symptoms, and lifestyle factors that may affect your blood sugar control, and share this information with your healthcare provider regularly.",
      "Consider participating in a clinical trial or research study investigating new treatments, interventions, or technologies for diabetes prevention or management. By contributing to scientific knowledge, you may gain access to innovative therapies and receive expert guidance from research staff.",
      "Stay connected with a multidisciplinary healthcare team that specializes in diabetes prevention and management, including endocrinologists, diabetes educators, nurses, and mental health professionals. Collaborate with each team member to address your unique needs, concerns, and goals.",
      "Seek emotional support from friends, family members, or support groups who understand your challenges and can provide empathy, encouragement, and practical assistance. Sharing your experiences and feelings openly can help alleviate stress and improve your overall well-being.",
      "Stay proactive and resilient in managing your health, even in the face of setbacks or challenges. Set realistic goals, celebrate progress, and remain committed to making positive changes that support your long-term health and well-being.",
    ],
  },
];

export default diabetesPrevention;
